### ISSUE TITLE
py.test import failure -> wrong seed ValueError

### ISSUE THREAD

**Issue by leodesigner** [arthurmensch/modl#11]
Hi,
I was trying to run py.test after install on Ubuntu 14.04 vagrant box
```
vagrant@deep-learning:~/modl$ py.test --pyargs modl
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/home/vagrant/modl/modl/__init__.py", line 1, in <module>
    from .dict_fact import DictFact
  File "/home/vagrant/modl/modl/dict_fact.py", line 8, in <module>
    from .utils.randomkit import RandomState
  File "/home/vagrant/modl/modl/utils/randomkit/__init__.py", line 1, in <module>
    from .random_fast import RandomState
ImportError: No module named random_fast                     
ERROR: could not load /home/vagrant/modl/modl/conftest.py

```
Could you please advise ?

**Comment by leodesigner** [comment]
Seems like cython modules was not compiled.
After make I am getting following errors from tests:
```
...

modl/utils/tests/test_system.py .
modl/utils/tests/test_utils.py .

=================================== FAILURES ===================================
______________________________ test_scale_patches ______________________________

    def test_scale_patches():
        patch_size = (8, 8, 3)
        n = 100
        shape = (n, ) + patch_size
        rs = check_random_state(0)
        X = rs.randn(*shape)
        Y = scale_patches(X, with_mean=True, with_std=True, channel_wise=True)
        assert_array_almost_equal(Y.mean(axis=(1, 2)), 0)
>       assert_array_almost_equal(np.sum(Y ** 2, axis=(1, 2)), 1 / 3)
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E       
E       (mismatch 100.0%)
E        x: array([[ 0.333333,  0.333333,  0.333333],
E              [ 0.333333,  0.333333,  0.333333],
E              [ 0.333333,  0.333333,  0.333333],...
E        y: array(0)

modl/preprocessing/tests/test_image.py:18: AssertionError
_____________________ test_dict_mf_reconstruction[masked] ______________________

solver = 'masked'

    @pytest.mark.parametrize("solver", solvers)
    def test_dict_mf_reconstruction(solver):
        X, Q = generate_synthetic()
        dict_mf = DictFact(n_components=4,
                           code_alpha=1e-4,
                           n_epochs=5,
                           comp_l1_ratio=0,
                           G_agg=solver_dict[solver]['G_agg'],
                           Dx_agg=solver_dict[solver]['Dx_agg'],
                           random_state=rng_global, reduction=1)
>       dict_mf.fit(X)

modl/tests/test_dict_fact.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
modl/dict_fact.py:193: in fit
    self.prepare(n_samples=X.shape[0], X=dict_init)
modl/dict_fact.py:364: in prepare
    self.replacement, random_seed)
modl/utils/randomkit/sampler.pyx:33: in modl.utils.randomkit.sampler.Sampler.__cinit__ (modl/utils/randomkit/sampler.c:2072)
    self.random_state = RandomState(seed=random_seed)
modl/utils/randomkit/random_fast.pyx:55: in modl.utils.randomkit.random_fast.RandomState.__init__ (modl/utils/randomkit/random_fast.c:2528)
    self.seed(seed)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   raise ValueError("Wrong seed")
E   ValueError: Wrong seed

modl/utils/randomkit/random_fast.pyx:72: ValueError
______________________ test_dict_mf_reconstruction[gram] _______________________


...
>   raise ValueError("Wrong seed")
E   ValueError: Wrong seed

modl/utils/randomkit/random_fast.pyx:72: ValueError
============================================== 29 failed, 23 passed, 4 skipped in 3.86 seconds =====
```

**Comment by leodesigner** [comment]
Moved to:
[issue 10](https://github.com/arthurmensch/modl/issues/10)
