### ISSUE TITLE
conftest.py broken. Can't run tests

### ISSUE THREAD

**Issue by dohmatob** [arthurmensch/modl#15]
```
(py3k) elvis@middle-earth:~/CODE/FORKED/modl$ make test
py.test --pyargs modl
Traceback (most recent call last):
  File "/home/elvis/anaconda2/envs/py3k/lib/python3.6/site-packages/_pytest/config.py", line 325, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/elvis/CODE/FORKED/modl/modl')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/elvis/anaconda2/envs/py3k/lib/python3.6/site-packages/_pytest/config.py", line 356, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/elvis/CODE/FORKED/modl/modl/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/elvis/anaconda2/envs/py3k/lib/python3.6/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/elvis/anaconda2/envs/py3k/lib/python3.6/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/home/elvis/CODE/FORKED/modl/modl/__init__.py", line 1, in <module>
    from .decomposition.dict_fact import DictFact
  File "/home/elvis/CODE/FORKED/modl/modl/decomposition/__init__.py", line 1, in <module>
    from .dict_fact import DictFact
  File "/home/elvis/CODE/FORKED/modl/modl/decomposition/dict_fact.py", line 13, in <module>
    from modl.utils.randomkit import RandomState
  File "/home/elvis/CODE/FORKED/modl/modl/utils/randomkit/__init__.py", line 1, in <module>
    from .random_fast import RandomState
ModuleNotFoundError: No module named 'modl.utils.randomkit.random_fast'
ERROR: could not load /home/elvis/CODE/FORKED/modl/modl/conftest.py
```

Removing the offending file `modl/conftest.py` and rerunning the tests works fine.

**Comment by arthurmensch** [comment]
Sorted
