### ISSUE TITLE
Installing on Mac OSX

### ISSUE THREAD

**Issue by seanlaw** [arthurmensch/modl#3]
Got as far as cloning and installing requirements and then

`pip install .`

Causes:

```
Processing /Users/seanlaw/Git/modl
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/var/folders/32/vghdf9rd4w1b2s9cpkf2v9nrcbdy1n/T/pip-jhMnUZ-build/setup.py", line 12, in <module>
LONG_DESCRIPTION = open('README.rst').read()
IOError: [Errno 2] No such file or directory: 'README.rst'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/32/vghdf9rd4w1b2s9cpkf2v9nrcbdy1n/T/pip-jhMnUZ-build/
```

I tried renaming the README in setup.py but still encountered problems.

**Comment by arthurmensch** [comment]
Should be sorted ?
